#ifndef USCOIN_CHAINPARAMSSEEDS_H
#define USCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the uscoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}, 8687}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}, 18687}
};
#endif // USCOIN_CHAINPARAMSSEEDS_H
